chore(swift): update swift to v2
Scalingo/go-utils pull request #393
Opened 2022-10-12 13:28 UTC by curzolapierre

- [ ] Add a changelog entry in `CHANGELOG.md`

2022-10-12 13:36 UTC, Soulou commented on storage/backend.go
> +	IsObjectExists(ctx context.Context, objectName string) (bool, error)
What about having a method `Info` which return a custom error if it does not exist?

(I'm not a fan of the `IsObjectExists` function name --'

2022-10-12 15:47 UTC, Soulou requested changes

2022-10-12 15:47 UTC, Soulou commented on storage/s3.go
> +		ContentType:   *res.ContentType,
Normally both API would also have a MD5/SHA256, could you check that and include it?

2022-10-12 16:33 UTC, Soulou requested changes

2022-10-12 16:33 UTC, Soulou commented on storage/s3.go
> +		Checksum:      *res.ChecksumSHA256,
Please add the type of CHecksum too ;-) ChecksumSHA256, it may evolve over time.

THanks!

2022-10-13 08:16 UTC, curzolapierre commented
Indeed it was a little more complicate than expected. Now it should be understood, thanks :+1: 

I put this here in case for me in the future: https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#checking-object-integrity-md5
About this ^
I guess logs-archives are not impacted by the 16MB limitation, but maybe we are in other case (e.g. backups).
If we want to check the integrity of each part of the upload we will have to support it specifically.

2022-10-13 08:27 UTC, Soulou approved these changes

2022-10-13 08:32 UTC, merged