feat(backend): Move and List func added
Scalingo/go-utils pull request #406
Opened 2022-10-26 12:31 UTC by QuentinEscudierScalingo

Fix #405

- [ ] Add a changelog entry in `CHANGELOG.md`

2022-10-26 14:20 UTC, EtienneM requested changes

2022-10-26 14:20 UTC, EtienneM commented on storage/swift.go
> +	return s.conn.ObjectMove(ctx, s.cfg.Container, srcPath, s.cfg.Container, dstPath)
I prefer we annotate the errors in this lib
```suggestion
	err := s.conn.ObjectMove(ctx, s.cfg.Container, srcPath, s.cfg.Container, dstPath)
	if err != nil {
		return errors.Wrapf(err, "fail to move the object")
	}
	return nil
```

2022-10-26 14:20 UTC, EtienneM commented on storage/s3.go
> +	srcPathWithBucket = fmt.Sprintf("%s/%s", s.cfg.Bucket, srcPathWithBucket)
```suggestion
	srcPathWithBucket := fmt.Sprintf("%s/%s", s.cfg.Bucket, fullPath(srcPath)
)
```

2022-10-26 14:20 UTC, EtienneM commented on storage/s3.go
> +	err = s.Delete(ctx, srcPath)
Please wrap this error

2022-10-26 14:20 UTC, EtienneM commented on storage/s3.go
> +func (s *S3) Move(ctx context.Context, srcPath, dstPath string) error {
No test for this function?

2022-10-26 14:20 UTC, EtienneM commented on storage/s3.go
> +func (s *S3) List(ctx context.Context, prefix string) ([]string, error) {
No test for this function?

2022-10-27 08:28 UTC, QuentinEscudierScalingo commented on storage/swift.go
> +		return nil, errors.Wrap(err, "fail to list objects in '%v'", prefix)
maybe you wanted to `errors.Wrapf` ?

2022-10-27 08:31 UTC, QuentinEscudierScalingo commented on storage/swift.go
> +		return nil, errors.Wrap(err, "fail to list objects in '%v'", prefix)
otherwise LGTM

2022-10-27 08:46 UTC, EtienneM approved these changes

2022-10-27 08:46 UTC, EtienneM commented on storage/swift.go
> +		return nil, errors.Wrap(err, "fail to list objects in '%v'", prefix)
Nice catch 👍🏾

2022-10-27 08:48 UTC, merged