feat(nsqconsumer): log the error by using root context (ErrCtx)
Scalingo/go-utils pull request #448
Opened 2022-12-19 13:55 UTC by curzolapierre

- [ ] Add a changelog entry in `CHANGELOG.md`

2022-12-21 17:28 UTC, Soulou requested changes
Once specs sorry but.. lack of specs :-D

2022-12-22 10:17 UTC, EtienneM commented on nsqconsumer/CHANGELOG.md
;)

```suggestion

## To be Released

* feat: Start unwraps errors to find noRetry field that can be wrapped in ErrCtx. Also use ErrCtx to enrich the logger
```

2022-12-22 10:54 UTC, curzolapierre commented
To be able to add spec and test `Start` method, I need to mock `nsq.Consumer`, but we cannot mock it as one of called method (`SetLogger`) use an non exported param. Hence the new call to
```go
nsq.NewConsumer(consumer.Topic, consumer.Channel, consumer.NsqConfig)
```
won't work.

2022-12-22 13:50 UTC, EtienneM commented on nsqconsumer/consumer.go
> +			errLogger.WithError(err).Error("message handling error - noretry")
picky picky: while you are on it :)
```suggestion
			errLogger.WithError(err).Error("Message handling error - noretry")
```

2022-12-22 13:50 UTC, EtienneM commented on nsqconsumer/consumer.go
> +		errLogger.WithError(err).Error("message handling error")
picky picky: while you are on it :)
```suggestion
		errLogger.WithError(err).Error("Message handling error")
```

2022-12-22 13:50 UTC, EtienneM commented on nsqconsumer/consumer.go
> +		c.logger.WithError(err).Error("failed to unmarshal message")
picky picky: while you are on it :)
```suggestion
		c.logger.WithError(err).Error("Fail to unmarshal message")
```

2022-12-22 13:50 UTC, EtienneM commented on nsqconsumer/consumer.go
> +		c.logger.WithError(err).Fatalf("Fail to connect to NSQ lookupd")
While we are on it, we shouldn't use `Fatalf`.

2022-12-23 09:49 UTC, EtienneM requested changes

2022-12-23 09:49 UTC, EtienneM commented on nsqconsumer/consumer.go
> +	if err = consumer.ConnectToNSQLookupds(c.NsqLookupdURLs); err != nil {
best practice: we don't use this construct, it's confusing

```suggestion
err = consumer.ConnectToNSQLookupds(c.NsqLookupdURLs)
	if err != nil {
```

2022-12-23 09:50 UTC, EtienneM commented on nsqconsumer/consumer.go
> +	//nolint:staticcheck,revive
You must explain why you add such a line

2022-12-23 10:24 UTC, EtienneM approved these changes

2023-01-10 08:22 UTC, Soulou approved these changes

2023-01-10 08:43 UTC, merged