feat(mongo/document/validation): Add distinction between internal and validation errors
Scalingo/go-utils pull request #552
Opened 2023-03-31 15:26 UTC by aurelien-reeves-scalingo

- [ ] Add a changelog entry in `CHANGELOG.md`

2023-07-07 13:52 UTC, aurelien-reeves-scalingo commented
Can't remember why I did not finished that one at that time.

As this is a breaking change, due to my change of team, I would not have the opportunity to go further with this (releasing it, updating impacted projects, ...).

So feel free to close it

2023-07-07 14:05 UTC, aurelien-reeves-scalingo commented on mongo/document/document.go
> +	Validate(ctx context.Context) (*ValidationErrors, error)
How would you do that?

2023-07-07 14:07 UTC, aurelien-reeves-scalingo commented on mongo/document/document.go
> +	Validate(ctx context.Context) (*ValidationErrors, error)
Oh, I remember.

Yes, we are able to make the distinction between a validation error and an internal error that would have happened during the save part.

But if an Internal error is raised as part of the validation process, we cannot

2023-07-07 14:12 UTC, aurelien-reeves-scalingo commented on mongo/document/document.go
> +	Validate(ctx context.Context) (*ValidationErrors, error)
It is the case here: https://github.com/Scalingo/appsdeck-database/pull/2728/files/85e7636eafd0515fa05f5cd5b02c7433cda9be46#diff-fb3dafe5420d7f35c4af24c65542d1d8e1aa6cfedffa11d8ddca206e91503f2aR148

There is an internal error part of a `validate` method. It is not a validation error, but as it is part of the validate method, it is processed as a validation error.

2023-07-10 07:19 UTC, EtienneM approved these changes

2023-07-10 07:19 UTC, EtienneM commented on mongo/document/document.go
> +	Validate(ctx context.Context) (*ValidationErrors, error)
Aaaaah yes I see the use case, I completely forgot about this. Thanks :)

2023-07-10 07:19 UTC, EtienneM requested changes
Oh no I can't validate, wait a sec :sweat_smile:

2023-07-10 07:22 UTC, EtienneM reviewed
`document.ValidationErrors` has been moved to `errors.ValidationErrors` but kept for retro-compatibility purpose.

If we release a new major version of this library, I think we should remove `document.ValidationErrors` and update the `Validate` signature to target `errors.ValidationErrors`. What do you think?

2023-07-10 07:23 UTC, aurelien-reeves-scalingo commented
> `document.ValidationErrors` has been moved to `errors.ValidationErrors` but kept for retro-compatibility purpose.
> 
> If we release a new major version of this library, I think we should remove `document.ValidationErrors` and update the `Validate` signature to target `errors.ValidationErrors`. What do you think?

Good idea.

What about opening a PR over that one?

2023-07-10 13:07 UTC, EtienneM approved these changes

2023-07-12 07:17 UTC, aurelien-reeves-scalingo commented
I did not realized how easy would be to remove the aliased type `document.ValidationErrors`.

@EtienneM could you please review it again?

2023-07-12 08:06 UTC, EtienneM approved these changes

2023-07-12 08:39 UTC, merged